### ISSUE TITLE
Change BUILD_STATIC to ON as default

### ISSUE THREAD

**Issue by tatatupi** [fabns-nano/advanced_docking_system#6]
https://github.com/fabns-nano/advanced_docking_system/blob/f73e0b7019dc81d6ea0599688554835d1c5b50c4/CMakeLists.txt#L10

**Comment by hudsonmiranda291** [comment]
To not perform any changes in the repo, we can just set this option to OFF um the parent CMakeLists that adds the ads subdirectory
